remote: False
hybrid: true
onsite: true

experience_level:
  internship: false
  entry: true
  associate: true
  mid_senior_level: true
  director: false
  executive: false

job_types:
  full_time: true
  contract: false
  part_time: false
  temporary: false
  internship: false
  other: false
  volunteer: true

date:
  all_time: true
  month: false
  week: false
  24_hours: true

positions:
  - Data Science
  - Machine Learning Operations
  - MLOps

locations:
  - Germany

apply_once_at_company: true

distance: 100

company_blacklist:
  - it-novum
  - allgeier
  - https://www.allgeier.com/
  - https://it-novum.com/

title_blacklist:
  - SAP

location_blacklist:
  - Brazil
  -

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 100

llm_model_type: anthropic
llm_model: 'claude-3.5-sonnet'
llm_api_url: 'https://api.anthropic.com/v1'

